-- MySQL Script generated by MySQL Workbench
-- Tue Jul  8 01:15:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema delivery_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delivery_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delivery_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `delivery_db` ;

-- -----------------------------------------------------
-- Table `delivery_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_db`.`user` ;

CREATE TABLE IF NOT EXISTS `delivery_db`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(29) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `delivery_db`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_db`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `delivery_db`.`restaurant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(205) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address` (`address` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `delivery_db`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_db`.`orders` ;

CREATE TABLE IF NOT EXISTS `delivery_db`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` VARCHAR(50) NULL DEFAULT 'entregado',
  `restaurant_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `restaurant_id` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `delivery_db`.`user` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `delivery_db`.`restaurant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `delivery_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_db`.`product` ;

CREATE TABLE IF NOT EXISTS `delivery_db`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `restaurant_id` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `delivery_db`.`restaurant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `delivery_db`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delivery_db`.`order_details` ;

CREATE TABLE IF NOT EXISTS `delivery_db`.`order_details` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `quantily` INT(11) NOT NULL,
  `unitary_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_details_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `delivery_db`.`orders` (`id`),
  CONSTRAINT `order_details_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `delivery_db`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
